version: '3.5'

services:
  mysql:
    image: mysql/mysql-server:5.7.21
    ports:
      - "3315:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=kwetter
      - MYSQL_PASSWORD=kwetter

  payara:
    build: .
    ports:
      - "10001:8080"
      - "4855:4848"
      - "8186:8181"
    links:
      - mysql
    depends_on:
      - mysql
